export class Constants {

  // public static clientRoot = 'http://localhost:4200/';
  // public static apiRoot = 'https://localhost:44320/api/';
  // public static apiAutoGeneratedRoot = 'https://localhost:44320';
  // public static stsAuthority = 'https://localhost:44309/';

  public static clientRoot = 'https://spell-it.co.uk/';
  public static apiRoot = 'https://bili-spell-api.azurewebsites.net/api/';
  public static apiAutoGeneratedRoot = 'https://bili-spell-api.azurewebsites.net';
  public static stsAuthority = 'https://bili-identity-server.azurewebsites.net/';

  public static clientId = 'spa-spelling-client';
}
