export class Constants {
  public static clientRoot = 'http://localhost:4200/';

  // public static apiRoot = 'https://securingangularappscoursev2-api.azurewebsites.net/api/';
  // public static stsAuthority = 'https://securingangularappscoursev2-sts.azurewebsites.net/';

  public static apiRoot = 'https://localhost:44320/api/';
  public static apiAutoGeneratedRoot = 'https://localhost:44320';
  public static stsAuthority = 'https://localhost:44309/';
  // public static stsAuthority = 'https://briannoyes.auth0.com/';

  public static clientId = 'spa-spelling-client';
  // public static clientId = 'Od8mbaoCGeXTF9ZWeQJspTTd7Qf1v1A7';
}
